config/routes.rb
Rails.application.routes.draw do
  resources :guards
  resources :appointments
  resources :workers
  resources :worker_types
  resources :medical_center_officials
  resources :medical_center_types
  resources :medical_centers
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "appointments#index"
end

app/models/medical_center_official.rb
class MedicalCenterOfficial < ApplicationRecord
  belongs_to :medical_center_type
  has_many :workers
  has_many :appointments
  validates :name, :address, :phone_number, :presence => true
end

app/controllers/medical_center_officials_controller.rb
class MedicalCenterOfficialsController < ApplicationController
  before_action :set_medical_center_official, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /medical_center_officials or /medical_center_officials.json
  def index
    @medical_center_officials = MedicalCenterOfficial.all
  end

  # GET /medical_center_officials/1 or /medical_center_officials/1.json
  def show
  end

  # GET /medical_center_officials/new
  def new
    @medical_center_official = MedicalCenterOfficial.new
  end

  # GET /medical_center_officials/1/edit
  def edit
  end

  # POST /medical_center_officials or /medical_center_officials.json
  def create
    @medical_center_official = MedicalCenterOfficial.new(medical_center_official_params)

    respond_to do |format|
      if @medical_center_official.save
        format.html { redirect_to @medical_center_official, notice: "Medical center official was successfully created." }
        format.json { render :show, status: :created, location: @medical_center_official }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medical_center_official.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_center_officials/1 or /medical_center_officials/1.json
  def update
    respond_to do |format|
      if @medical_center_official.update(medical_center_official_params)
        format.html { redirect_to @medical_center_official, notice: "Medical center official was successfully updated." }
        format.json { render :show, status: :ok, location: @medical_center_official }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medical_center_official.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_center_officials/1 or /medical_center_officials/1.json
  def destroy
    @medical_center_official.destroy
    respond_to do |format|
      format.html { redirect_to medical_center_officials_url, notice: "Medical center official was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_center_official
      @medical_center_official = MedicalCenterOfficial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_center_official_params
      params.require(:medical_center_official).permit(:name, :description, :address, :phone_number, :medical_center_type_id)
    end
end

app/helpers/medical_center_officials_helper.rb
module MedicalCenterOfficialsHelper
end

app/views/medical_center_officials/_form.html.erb
<%= form_with(model: medical_center_official) do |form| %>
  <% if medical_center_official.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_center_official.errors.count, "error") %> prohibited this medical_center_official from being saved:</h2>

      <ul>
        <% medical_center_official.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :medical_center_type_id %>
    <%= form.text_field :medical_center_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medical_center_officials/edit.html.erb
<h1>Editing Medical Center Official</h1>

<%= render 'form', medical_center_official: @medical_center_official %>

<%= link_to 'Show', @medical_center_official %> |
<%= link_to 'Back', medical_center_officials_path %>

app/views/medical_center_officials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medical Center Officials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Medical center type</th>
      <th>Number of appointments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_center_officials.each do |medical_center_official| %>
      <tr>
        <td><%= medical_center_official.name %></td>
        <td><%= medical_center_official.description %></td>
        <td><%= medical_center_official.address %></td>
        <td><%= medical_center_official.phone_number %></td>
        <td><%= medical_center_official.medical_center_type_id %></td>
        <th><%= medical_center_official.appointments.count %></th>
        <th><%= medical_center_official.guards.count %></th>
        <td><%= link_to 'Show', medical_center_official %></td>
        <td><%= link_to 'Edit', edit_medical_center_official_path(medical_center_official) %></td>
        <td><%= link_to 'Destroy', medical_center_official, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medical Center Official', new_medical_center_official_path %>

app/views/medical_center_officials/new.html.erb
<h1>New Medical Center Official</h1>

<%= render 'form', medical_center_official: @medical_center_official %>

<%= link_to 'Back', medical_center_officials_path %>

app/views/medical_center_officials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medical_center_official.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @medical_center_official.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @medical_center_official.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @medical_center_official.phone_number %>
</p>

<p>
  <strong>Medical center type:</strong>
  <%= @medical_center_official.medical_center_type_id %>
</p>

<%= link_to 'Edit', edit_medical_center_official_path(@medical_center_official) %> |
<%= link_to 'Back', medical_center_officials_path %>